---
- name: Add User with Password to Sudoers
  hosts: 192.168.0.94
  become: true
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    username: gcs_scan
    gcs_scan_password: $1$SomeSalt$3qQvRlVMNbQwLs/ap404E.
    
   #remote_user: root
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ gcs_scan_password }}"
        update_password: on_create
        groups: "{{ super_group }}"
        append: yes

    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
        
   - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
     notify:
       - restart ssh
 
   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify:
       - restart ssh
 
  handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted
