---
- name: Delete a User
  hosts: debian_endpoints
  become: true
  tasks:
    - name: user example not present
      ansible.builtin.user:
        name: user
        state: "absent"
        remove: true
