---
- name: Update and Upgrade apt Packages and Install latest Nmap
  hosts: debian_endpoints
  vars:
      package: nmap
      state: latest
  become: true
  tasks:
    - name: Update and Upgrade apt Packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    
    - name: Install the {{ state }} version of {{ package }} using apt
      apt:
        name: "{{ package }}"
        state: "{{ state }}"